### ISSUE TITLE
SchemaEditor not working it goes to the error page with following exception

### ISSUE THREAD

**Issue by vaibhavcse30** [OpenIotOrg/openiot#111]
NFO  [stdout](scheduler_Worker-3) [CAS] INFO  o.o.s.o.OpenIoTServicesManagerImpl - Loaded 10 services.
NFO  [stdout](http--127.0.0.1-8080-110) [LSM-S] INFO  o.openiot.lsm.manager.SensorManager - getting tike
id
NFO  [stdout](http--127.0.0.1-8080-88) [LSM-S] INFO  o.openiot.lsm.manager.SensorManager - deleting tike
id
NFO  [stdout](http--127.0.0.1-8080-142) [LSM-S] INFO  o.openiot.lsm.manager.SensorManager - insert tripl
ttp://localhost:8890/OpenIoT/OAuth#
NFO  [stdout](http--127.0.0.1-8080-142) [LSM-S] INFO  o.openiot.lsm.manager.SensorManager - Insert tripl
p://localhost:8890/OpenIoT/OAuth# successfully
NFO  [stdout](http--127.0.0.1-8080-142) [LSM-S] INFO  o.openiot.lsm.manager.SensorManager - getting tike

NFO  [stdout](http--127.0.0.1-8080-142) [LSM-S] INFO  o.openiot.lsm.manager.SensorManager - insert tripl
ttp://localhost:8890/OpenIoT/OAuth#
NFO  [stdout](http--127.0.0.1-8080-142) [LSM-S] INFO  o.openiot.lsm.manager.SensorManager - Insert tripl
p://localhost:8890/OpenIoT/OAuth# successfully
NFO  [stdout](http--127.0.0.1-8443-3) [CAS] INFO  o.o.s.o.OpenIoTCentralAuthenticationServiceImpl - Gran
ket [ST-32-To16Phg7dH3eoPWu0UjS-localhost] for service [https://localhost:8443/openiot-cas/oauth2.0/callb
or user [admin]
NFO  [stdout](http--127.0.0.1-8080-142) [LSM-S] INFO  o.openiot.lsm.manager.SensorManager - getting tike
id
NFO  [stdout](http--127.0.0.1-8443-3) [CAS] INFO  c.g.i.a.s.Slf4jLoggingAuditTrailManager - Audit trail

NFO  [stdout](http--127.0.0.1-8443-3) =============================================================
NFO  [stdout](http--127.0.0.1-8443-3) WHO: admin
NFO  [stdout](http--127.0.0.1-8443-3) WHAT: ST-32-To16Phg7dH3eoPWu0UjS-localhost for https://localhost:8
/oauth2.0/callbackAuthorize
NFO  [stdout](http--127.0.0.1-8443-3) ACTION: SERVICE_TICKET_CREATED
NFO  [stdout](http--127.0.0.1-8443-3) APPLICATION: CAS
NFO  [stdout](http--127.0.0.1-8443-3) WHEN: Mon Jul 06 11:53:59 IST 2015
NFO  [stdout](http--127.0.0.1-8443-3) CLIENT IP ADDRESS: 127.0.0.1
NFO  [stdout](http--127.0.0.1-8443-3) SERVER IP ADDRESS: 127.0.0.1
NFO  [stdout](http--127.0.0.1-8443-3) =============================================================
NFO  [stdout](http--127.0.0.1-8443-3)
NFO  [stdout](http--127.0.0.1-8443-3)
NFO  [stdout](http--127.0.0.1-8443-3) [CAS] INFO  c.g.i.a.s.Slf4jLoggingAuditTrailManager - Audit trail

NFO  [stdout](http--127.0.0.1-8443-3) =============================================================
NFO  [stdout](http--127.0.0.1-8443-3) WHO: admin
NFO  [stdout](http--127.0.0.1-8443-3) WHAT: ST-32-To16Phg7dH3eoPWu0UjS-localhost for https://localhost:8
/oauth2.0/callbackAuthorize
NFO  [stdout](http--127.0.0.1-8443-3) ACTION: SERVICE_TICKET_CREATED
NFO  [stdout](http--127.0.0.1-8443-3) APPLICATION: CAS
NFO  [stdout](http--127.0.0.1-8443-3) WHEN: Mon Jul 06 11:53:59 IST 2015
NFO  [stdout](http--127.0.0.1-8443-3) CLIENT IP ADDRESS: 127.0.0.1
NFO  [stdout](http--127.0.0.1-8443-3) SERVER IP ADDRESS: 127.0.0.1
NFO  [stdout](http--127.0.0.1-8443-3) =============================================================
NFO  [stdout](http--127.0.0.1-8443-3)
NFO  [stdout](http--127.0.0.1-8443-3)
NFO  [stdout](http--127.0.0.1-8080-22) [LSM-S] INFO  o.openiot.lsm.manager.SensorManager - getting tiket

NFO  [stdout](http--127.0.0.1-8080-22) [LSM-S] INFO  o.openiot.lsm.manager.SensorManager - getting tiket
d
NFO  [stdout](http--127.0.0.1-8443-2) [CAS] ERROR o.j.c.s.o.w.OAuth20AccessTokenController - Wrong clien
maEditor-secret for service description : schemaEditor.secret
RROR [stderr](http--127.0.0.1-8080-48) org.apache.shiro.authc.AuthenticationException: org.pac4j.core.ex
alException: org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract a token from
nvalid_request'
RROR [stderr](http--127.0.0.1-8080-48)   at io.buji.pac4j.ClientRealm.doGetAuthenticationInfo(ClientReal

RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.realm.AuthenticatingRealm.getAuthentication
tingRealm.java:568)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingl
ation(ModularRealmAuthenticator.java:180)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthe
RealmAuthenticator.java:267)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.authc.AbstractAuthenticator.authenticate(Ab
ator.java:198)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.mgt.AuthenticatingSecurityManager.authentic
ingSecurityManager.java:106)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSec
va:270)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.subject.support.DelegatingSubject.login(Del
java:256)
RROR [stderr](http--127.0.0.1-8080-48)   at io.buji.pac4j.ClientFilter.onAccessDenied(ClientFilter.java:

RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.filter.AccessControlFilter.onAccessDeni
lFilter.java:133)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(
lter.java:162)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChain
atchingFilter.java:203)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(Pat
.java:178)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(A
a:131)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(O
lter.java:125)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(Pro
.java:66)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChai
Filter.java:449)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(Abst
.java:365)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.subject.support.SubjectCallable.doCall(Subj
a:90)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.subject.support.SubjectCallable.call(Subjec
83)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.subject.support.DelegatingSubject.execute(D
t.java:383)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInt
hiroFilter.java:362)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(O
lter.java:125)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.catalina.core.ApplicationFilterChain.internalDoFi
nFilterChain.java:280)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.catalina.core.ApplicationFilterChain.doFilter(App
hain.java:248)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.catalina.core.StandardWrapperValve.invoke(Standar
ava:275)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.catalina.core.StandardContextValve.invoke(Standar
ava:161)
RROR [stderr](http--127.0.0.1-8080-48)   at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(We
alve.java:50)
RROR [stderr](http--127.0.0.1-8080-48)   at org.jboss.as.web.security.SecurityContextAssociationValve.in
ntextAssociationValve.java:153)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.catalina.core.StandardHostValve.invoke(StandardHo
5)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorRepo
2)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.catalina.core.StandardEngineValve.invoke(Standard
a:109)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAd

RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.coyote.http11.Http11Processor.process(Http11Proce

RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHand
p11Protocol.java:671)
RROR [stderr](http--127.0.0.1-8080-48)   at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoin

RROR [stderr](http--127.0.0.1-8080-48)   at java.lang.Thread.run(Thread.java:745)
RROR [stderr](http--127.0.0.1-8080-48) Caused by: org.pac4j.core.exception.TechnicalException: org.scrib
uthException: Response body is incorrect. Can't extract a token from this: 'error=invalid_request'
RROR [stderr](http--127.0.0.1-8080-48)   at org.pac4j.oauth.client.BaseOAuthClient.retrieveUserProfile(B
java:166)
RROR [stderr](http--127.0.0.1-8080-48)   at org.pac4j.oauth.client.BaseOAuthClient.retrieveUserProfile(B
java:44)
RROR [stderr](http--127.0.0.1-8080-48)   at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.j

RROR [stderr](http--127.0.0.1-8080-48)   at io.buji.pac4j.ClientRealm.internalGetAuthenticationInfo(Clie
9)
RROR [stderr](http--127.0.0.1-8080-48)   at io.buji.pac4j.ClientRealm.doGetAuthenticationInfo(ClientReal

RROR [stderr](http--127.0.0.1-8080-48)   ... 36 more
RROR [stderr](http--127.0.0.1-8080-48) Caused by: org.scribe.exceptions.OAuthException: Response body is
't extract a token from this: 'error=invalid_request'
RROR [stderr](http--127.0.0.1-8080-48)   at org.scribe.extractors.TokenExtractor20Impl.extract(TokenExtr
a:33)
RROR [stderr](http--127.0.0.1-8080-48)   at org.scribe.oauth.ExtendedOAuth20ServiceImpl.getAccessToken(E
erviceImpl.java:55)
RROR [stderr](http--127.0.0.1-8080-48)   at org.pac4j.oauth.client.BaseOAuth20Client.getAccessToken(Base
ava:106)
RROR [stderr](http--127.0.0.1-8080-48)   at org.pac4j.oauth.client.BaseOAuthClient.retrieveUserProfile(B
java:163)
RROR [stderr](http--127.0.0.1-8080-48)   ... 40 more

**Comment by premjayaraman** [comment]
This looks to be a problem with the security configuration.

Could you please confirm the following
1. The schema editor key and secret in openiot.properties
2. The same from security.management web interface
3. The same from security.config.ini the jboss configuration folder.

The auth details in these 3 places need to match. Also the user will need to have appropriate permissions to insert into lsm and use the schema editor. Check the wiki for these instructions.

/prem

<div>-------- Original message --------</div><div>From: vaibhavcse30 notifications@github.com </div><div>Date:06/07/2015  16:50  (GMT+10:00) </div><div>To: OpenIotOrg/openiot openiot@noreply.github.com </div><div>Subject: [openiot] SchemaEditor not working it alwasy goes to the error page
  with following exception (#111) </div><div>
</div>NFO stdout [CAS] INFO o.o.s.o.OpenIoTServicesManagerImpl - Loaded 10 services.
NFO stdout [LSM-S] INFO o.openiot.lsm.manager.SensorManager - getting tike
id
NFO stdout [LSM-S] INFO o.openiot.lsm.manager.SensorManager - deleting tike
id
NFO stdout [LSM-S] INFO o.openiot.lsm.manager.SensorManager - insert tripl
ttp://localhost:8890/OpenIoT/OAuth#
NFO stdout [LSM-S] INFO o.openiot.lsm.manager.SensorManager - Insert tripl
p://localhost:8890/OpenIoT/OAuth# successfully
NFO stdout [LSM-S] INFO o.openiot.lsm.manager.SensorManager - getting tike

NFO stdout [LSM-S] INFO o.openiot.lsm.manager.SensorManager - insert tripl
ttp://localhost:8890/OpenIoT/OAuth#
NFO stdout [LSM-S] INFO o.openiot.lsm.manager.SensorManager - Insert tripl
p://localhost:8890/OpenIoT/OAuth# successfully
NFO stdout [CAS] INFO o.o.s.o.OpenIoTCentralAuthenticationServiceImpl - Gran
ket [ST-32-To16Phg7dH3eoPWu0UjS-localhost] for service [https://localhost:8443/openiot-cas/oauth2.0/callb
or user [admin]
NFO stdout [LSM-S] INFO o.openiot.lsm.manager.SensorManager - getting tike
id
NFO stdout [CAS] INFO c.g.i.a.s.Slf4jLoggingAuditTrailManager - Audit trail

NFO stdout =============================================================
NFO stdout WHO: admin
NFO stdout WHAT: ST-32-To16Phg7dH3eoPWu0UjS-localhost for https://localhost:8
/oauth2.0/callbackAuthorize
NFO stdout ACTION: SERVICE_TICKET_CREATED
NFO stdout APPLICATION: CAS
NFO stdout WHEN: Mon Jul 06 11:53:59 IST 2015
NFO stdout CLIENT IP ADDRESS: 127.0.0.1
NFO stdout SERVER IP ADDRESS: 127.0.0.1
NFO stdout =============================================================
NFO stdout
NFO stdout
NFO stdout [CAS] INFO c.g.i.a.s.Slf4jLoggingAuditTrailManager - Audit trail

NFO stdout =============================================================
NFO stdout WHO: admin
NFO stdout WHAT: ST-32-To16Phg7dH3eoPWu0UjS-localhost for https://localhost:8
/oauth2.0/callbackAuthorize
NFO stdout ACTION: SERVICE_TICKET_CREATED
NFO stdout APPLICATION: CAS
NFO stdout WHEN: Mon Jul 06 11:53:59 IST 2015
NFO stdout CLIENT IP ADDRESS: 127.0.0.1
NFO stdout SERVER IP ADDRESS: 127.0.0.1
NFO stdout =============================================================
NFO stdout
NFO stdout
NFO stdout [LSM-S] INFO o.openiot.lsm.manager.SensorManager - getting tiket

NFO stdout [LSM-S] INFO o.openiot.lsm.manager.SensorManager - getting tiket
d
NFO stdout [CAS] ERROR o.j.c.s.o.w.OAuth20AccessTokenController - Wrong clien
maEditor-secret for service description : schemaEditor.secret
RROR stderr org.apache.shiro.authc.AuthenticationException: org.pac4j.core.ex
alException: org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract a token from
nvalid_request'
RROR stderr at io.buji.pac4j.ClientRealm.doGetAuthenticationInfo(ClientReal

RROR stderr at org.apache.shiro.realm.AuthenticatingRealm.getAuthentication
tingRealm.java:568)
RROR stderr at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingl
ation(ModularRealmAuthenticator.java:180)
RROR stderr at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthe
RealmAuthenticator.java:267)
RROR stderr at org.apache.shiro.authc.AbstractAuthenticator.authenticate(Ab
ator.java:198)
RROR stderr at org.apache.shiro.mgt.AuthenticatingSecurityManager.authentic
ingSecurityManager.java:106)
RROR stderr at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSec
va:270)
RROR stderr at org.apache.shiro.subject.support.DelegatingSubject.login(Del
java:256)
RROR stderr at io.buji.pac4j.ClientFilter.onAccessDenied(ClientFilter.java:

RROR stderr at org.apache.shiro.web.filter.AccessControlFilter.onAccessDeni
lFilter.java:133)
RROR stderr at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(
lter.java:162)
RROR stderr at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChain
atchingFilter.java:203)
RROR stderr at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(Pat
.java:178)
RROR stderr at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(A
a:131)
RROR stderr at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(O
lter.java:125)
RROR stderr at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(Pro
.java:66)
RROR stderr at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChai
Filter.java:449)
RROR stderr at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(Abst
.java:365)
RROR stderr at org.apache.shiro.subject.support.SubjectCallable.doCall(Subj
a:90)
RROR stderr at org.apache.shiro.subject.support.SubjectCallable.call(Subjec
83)
RROR stderr at org.apache.shiro.subject.support.DelegatingSubject.execute(D
t.java:383)
RROR stderr at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInt
hiroFilter.java:362)
RROR stderr at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(O
lter.java:125)
RROR stderr at org.apache.catalina.core.ApplicationFilterChain.internalDoFi
nFilterChain.java:280)
RROR stderr at org.apache.catalina.core.ApplicationFilterChain.doFilter(App
hain.java:248)
RROR stderr at org.apache.catalina.core.StandardWrapperValve.invoke(Standar
ava:275)
RROR stderr at org.apache.catalina.core.StandardContextValve.invoke(Standar
ava:161)
RROR stderr at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(We
alve.java:50)
RROR stderr at org.jboss.as.web.security.SecurityContextAssociationValve.in
ntextAssociationValve.java:153)
RROR stderr at org.apache.catalina.core.StandardHostValve.invoke(StandardHo
5)
RROR stderr at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorRepo
2)
RROR stderr at org.apache.catalina.core.StandardEngineValve.invoke(Standard
a:109)
RROR stderr at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAd

RROR stderr at org.apache.coyote.http11.Http11Processor.process(Http11Proce

RROR stderr at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHand
p11Protocol.java:671)
RROR stderr at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoin

RROR stderr at java.lang.Thread.run(Thread.java:745)
RROR stderr Caused by: org.pac4j.core.exception.TechnicalException: org.scrib
uthException: Response body is incorrect. Can't extract a token from this: 'error=invalid_request'
RROR stderr at org.pac4j.oauth.client.BaseOAuthClient.retrieveUserProfile(B
java:166)
RROR stderr at org.pac4j.oauth.client.BaseOAuthClient.retrieveUserProfile(B
java:44)
RROR stderr at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.j

RROR stderr at io.buji.pac4j.ClientRealm.internalGetAuthenticationInfo(Clie
9)
RROR stderr at io.buji.pac4j.ClientRealm.doGetAuthenticationInfo(ClientReal

RROR stderr ... 36 more
RROR stderr Caused by: org.scribe.exceptions.OAuthException: Response body is
't extract a token from this: 'error=invalid_request'
RROR stderr at org.scribe.extractors.TokenExtractor20Impl.extract(TokenExtr
a:33)
RROR stderr at org.scribe.oauth.ExtendedOAuth20ServiceImpl.getAccessToken(E
erviceImpl.java:55)
RROR stderr at org.pac4j.oauth.client.BaseOAuth20Client.getAccessToken(Base
ava:106)
RROR stderr at org.pac4j.oauth.client.BaseOAuthClient.retrieveUserProfile(B
java:163)
RROR stderr ... 40 more

**Comment by vaibhavcse30** [comment]
Thanks  a lot . There was a mismatch between the keys at security.config.ini and openiot.properties
Resolved my issue.
Thanks and Regards,
Vaibhav.
