### ISSUE TITLE
Request Presentation

### ISSUE THREAD

**Issue by keithsptr** [OpenIotOrg/openiot#38]
Hi,

I did a try out of OpenIoT Platform and the Request Presentation seems not to be working or else I did something wrong.

I went to the Request Definition and did a design (find attached) using Lausanne Sensor. Then I went to the Request Presentation, logged in and opened the application. 

The Result that I am seeing on the screen is No data Available. I already tried using other sensor data (Vilnius etc) and the result is the same

![requestpresentation](https://f.cloud.github.com/assets/3962994/1654280/311bb08e-5b48-11e3-850b-ddb72c5ca3e8.png)
![requestdefinition](https://f.cloud.github.com/assets/3962994/1654281/311c78e8-5b48-11e3-8337-75ee414625f8.png)

**Comment by premjayaraman** [comment]
Hi Keith,

I think the issue is with selection filter. I might be wrong. Could you try this

The selection filter will need to have a date comparison operator.
Under comparator drag the date between option.
Connect it to select filter
Click the date compare and select the dates for computation to be between 6 and 8th November 2013.

OR

Remove the selection operator completely and then run the code.

Also could you cut and paste the SPARQL query here so that we can investigate its correctness.

Cheers
Prem
