### ISSUE TITLE
LSM Server Errors

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#41]
1. Trying to register a new sensor resource with a local virtuoso instance. The following error appears
   ![image](https://f.cloud.github.com/assets/2141439/1669753/0bed422a-5c81-11e3-973b-207e0a73e337.png)

![image](https://f.cloud.github.com/assets/2141439/1669756/10ee3446-5c81-11e3-825e-8be8cab41976.png)
1. User Authentication Fails
   In ObjectServlet.java under org.openiot.lsm.http (LSM-Server), the following code refers to lsm-deri.ie and the userAuthentication code. Since there is no local datastore with LSM, its obvious a no table found error is thrown. In the userAuthentication code, again, the SQL’s are hard coded e.g. deri.dba.users 
   Both Screenshots below

![image](https://f.cloud.github.com/assets/2141439/1669760/2ff13e7e-5c81-11e3-9cf7-78c45b4c63f3.png)
![image](https://f.cloud.github.com/assets/2141439/1669762/31fa3c2a-5c81-11e3-935a-7602b81609b9.png)
1. After testing the LSM server deployed and TOMCAT and accessing it with LSM-Client code, a  sensor registration message returns the sensor resource id to be 
   http://lsm.deri.ie/resource/78293157385650

Should this not again point to http://localhost/resource/resourceID?
1. Finally, Both the LSM Client and LSM Server has too much hardcoded references to lsm.deri.ie instance. 

I suppose the data generated will be stored on a local virtuoso datastore. This way all references should point to the data store right?

There are also missing table creation scripts to support the LSM-Server and virtuoso interactions.

**Comment by nmqhoan** [comment]
Hi Prem,
The http://lsm.deri.ie/resource is just a prefix we define for all sensors using LSM ontology. So in case you want to store data into your LSM instance, it still be fine.
At the beginning, we have to authenticate all the OpenIoT users want to access LSM server. This is why you see the authentication step in the code. The users data are stored in LSM server.  Since we are in the final step of LSM and Privacy&Security integration, I will remove all the authentication code and update the new version of lsm-light.server as well as lsm-light.client. When the authentication code is removed, the problem is solved.

**Comment by premjayaraman** [comment]
thanks hoan for the update.

Will wait for the new version and report back any issue I face.
