### ISSUE TITLE
XGSN / SecurityManagement: How to configure both

### ISSUE THREAD

**Issue by hylkevds** [OpenIotOrg/openiot#77]
I need a step-by-step guide what to configure in both the SecurityManagement web-app and in XGSN so that XGSN can push data to LSM.

Same goes for the other services.

**Comment by mdii** [comment]
Configuration for XGSN:
1. Modify the URLs in src/main/resources/rest-client.ini so that they match your setup. 

Configuration in Security management web app:
1. Create an account for with username 'gsnuser' and password 'gsnpass' in "Sign Up" page.
2. Log in
3. Create a Rest service with key 'xgsn' and secret 'xgsn.secret'
4. By default the required permissions for lsm-server are created on lsm-server startup if the security graph is empty. 
5. Create a role for xgsn on service "lsm-server" with name, for example, "XGSN-Role" and assign the permission "lsm-light.server:all" to it.
6. Assign "XGSN-Role" to user "gsnuser"

**Comment by hylkevds** [comment]
Thanks, that worked.

Config files in `src/main/resources/rest-client.ini` are problematic, since they can only be changed at build time. Can you make it so any config files in resources are only used for default values, and all config files in the `/conf` directory override those?

Are the `application.conf` and `openiot.properties` in `src/main/resources` used for anything? If so, then they should really also be moved to /conf so they can be changed without rebuilding.
I also get the following errors, that are probably related:

```
10:48:46.897 [qtp1395737844-26] DEBUG o.o.commons.util.PropertyManagement - jbosServerConfigDir:null/openiot.properties
10:48:46.897 [qtp1395737844-26] ERROR o.o.commons.util.PropertyManagement - Unable to find file: null/openiot.properties
10:48:46.897 [qtp1395737844-26] DEBUG o.o.commons.util.PropertyManagement - jbosServerConfigDir:null/openiot.properties
10:48:46.897 [qtp1395737844-26] ERROR o.o.commons.util.PropertyManagement - Unable to find file: null/openiot.properties
```

**Comment by hylkevds** [comment]
I also noticed the following warning that might be related:

```
11:18:16.480 [ qtp603766490-23] WARN  o.o.s.client.AccessControlUtilRest - casOauthClient.key.null or/and casOauthClient.secret.null is not set in the global properties file
```

**Comment by mdii** [comment]
Thanks for the suggestions! 
I added the ability to read the ini config file from `conf` directory. The filename however, is `conf/rest-client-xgsn.ini`. When this file cannot be found, it will fall back to `rest-client.ini` in the class path. Please test with this modification (security-client module must be reinstalled).

The debug messages from PropertyManagement are normal since XGSN is not deployed in JBoss. Nevertheless, I changed the debug level from ERROR to WARN when _openiot.properties_ cannot be found.

The WARN message from AccessControlUtilRest is also fixed.

**Comment by nkef** [comment]
Hylke, is this issue satisfied? Should we close it?

**Comment by hylkevds** [comment]
Yes, this one can be closed. I've opened another one for the other components.
