### ISSUE TITLE
Request Definition: sensor instance doesn't show AirTemperature and Humidity property

### ISSUE THREAD

**Issue by palban** [OpenIotOrg/openiot#98]
Hello,
when I create a sensor instance all work fine and i save file.metadata with sensor description.
When i register the file.metadata to lsm all work fine, but when i drag & drop a sensor instance in RequestDefinition the sensor show only lat and lon property.

Can u help me pls?

Thanks in advanced

**Comment by nkef** [comment]
Hi,

Usually this happens if you have not produced any data from the sensor. Start producing data (pussing data from X-GSN to LSM-light) and come back to us if the issue persist. 
For these kind of questions (that don't identify specific issue) please use the [OpenIoT mailing lists](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists) )

Best Regards,
Nikos
